name: Merge custom-mods to main

on:
  push:
    branches:
      - custom-mods
  workflow_dispatch:
  schedule:
    - cron: '27 3 * * 1'

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Save current README.md
        run: |
          cp README.md /tmp/README.md || echo "No README.md to save"

      - name: Merge custom-mods (README bleibt erhalten)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin custom-mods:custom-mods
          git merge --allow-unrelated-histories --no-edit custom-mods || true
          # README.md zurückkopieren
          cp /tmp/README.md README.md || echo "No README.md to restore"

      - name: Commit & Push
        run: |
          git add README.md
          git commit -m "Preserve README.md from main during merge" || echo "No changes to commit"
          git push origin main
