# .github/workflows/update-custom-mods.yml
name: Update custom-mods after betterfox-upstream

on:
  workflow_run:
    workflows: ['Sync betterfox-upstream']
    types:
      - completed
  workflow_dispatch:

jobs:
  update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout custom-mods branch
        uses: actions/checkout@v4
        with:
          ref: custom-mods
          token: ${{ secrets.GH_PAT }}

      - name: Checkout betterfox-upstream branch
        uses: actions/checkout@v4
        with:
          ref: betterfox-upstream
          path: betterfox-upstream
          token: ${{ secrets.GH_PAT }}

      - name: Checkout arkenfox-upstream branch
        uses: actions/checkout@v4
        with:
          ref: arkenfox-upstream
          path: arkenfox-upstream
          token: ${{ secrets.GH_PAT }}

      - name: Overwrite user.js from betterfox-upstream, updater.bat & prefsCleaner.bat from arkenfox-upstream
        run: |
          cp betterfox-upstream/user.js ./user.js
          cp arkenfox-upstream/prefsCleaner.bat ./prefsCleaner.bat

      - name: Remove excluded files/folders before commit
        run: |
          rm -rf personal/
          rm -rf zen/
          rm -rf .github/ISSUE_TEMPLATE/
          rm -f .github/FUNDING.yml
          rm -f Fastfox.js
          rm -f Peskyfox.js
          rm -f Securefox.js
          rm -f Smoothfox.js
          rm -f install.py
          rm -f policies.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add user.js
          git commit -m "Update user.js from betterfox-upstream [auto-sync]" || echo "No changes to commit"
          git push origin custom-mods
